### ISSUE TITLE
when I go to the last step, it reminds me  <拒绝访问>

### ISSUE THREAD

**Issue by leoliuu** [levihsu/OOTDiffusion#101]
C:\WINDOWS\system32>cd C:\Users\ASUS\OOTDiffusion\run

C:\Users\ASUS\OOTDiffusion\run>python run_ootd.py --model_path <C:\Users\ASUS\OOTDiffusion\run\examples\model> --cloth_path <C:\Users\ASUS\OOTDiffusion\run\examples\garment> --scale 2.0 --sample 4
拒绝访问。

**Comment by leoliuu** [comment]
I have used the Administrator model

**Comment by cunfeng1111** [comment]
try C:\Users\ASUS\OOTDiffusion\run>python run_ootd.py --model_path C:\Users\ASUS\OOTDiffusion\run\examples\model --cloth_path C:\Users\ASUS\OOTDiffusion\run\examples\garment --scale 2.0 --sample 4
