### ISSUE TITLE
vae的scaling_factor对哪些latents做了缩放？

### ISSUE THREAD

**Issue by trikim** [levihsu/OOTDiffusion#105]
如题，从推理代码上看，只对原模特图image_ori_latents做了缩放，用于后面和（1 - mask_latents）相乘，而其他的vton_latents和garm_latents都没有看到做缩放，这是什么原因呢？有对比过对其他latents也做缩放的效果吗？

**Comment by levihsu** [comment]
你好 这里做缩放是为了后续减轻vae重建unmasked region的损失 不太理解对其他latents做缩放的意义

**Comment by liupengcnu** [comment]
借楼请教一个问题，在训练过程中，是不是跟推理过程一样，只对原模特图image_ori_latents做了缩放，而其他的vton_latents和garm_latents都没有看到做缩放？
