### ISSUE TITLE
_cuda_setDevice？？？

### ISSUE THREAD

**Issue by qing-tian-meng-ying** [levihsu/OOTDiffusion#110]
{AttributeError}module 'torch._C' has no attribute '_cuda_setDevice'
![1710422217232](https://github.com/levihsu/OOTDiffusion/assets/113198227/cc4d8cd0-5aa4-4340-aa4f-66ef8754dce1)
明明是官方指定的torch版本，但跑起来就有问题了？

**Comment by daiguoxi** [comment]
你可以卸掉以前的，用conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia试一下，我也是遇到这个问题，用这个后解决了
