### ISSUE TITLE
How to construct the input for Denoising unet in training process

### ISSUE THREAD

**Issue by liupengcnu** [levihsu/OOTDiffusion#111]
Hi, Dr Xu, In your paper, you said that ". Then we concatenate E(xm) with a Gaussian noise ϵ as the input latent zT for the denoising Unet",  I want to know that whether you generate a noise randomly and then concatenate with  E(xm) together as input directly in your training process? I have trained with this way, but the result is bad. So, I want to know that how to construct the input for Denoising unet in training process?

**Comment by levihsu** [comment]
Hi. The training input is the noisy ground truth latent concatenated with the masked human latent (for self-supervised learning)

**Comment by liupengcnu** [comment]
> Hi. The training input is the noisy ground truth latent concatenated with the masked human latent (for self-supervised learning)
The noisy ground truth latent is the the noise generated randomly? or the noise_scheduler.add_noise(image_ori_latents, noise, timesteps)

**Comment by levihsu** [comment]
ground truth + noise

**Comment by liupengcnu** [comment]
> ground truth + noise

The add process is perform as "noise_scheduler.add_noise(ground truth, noise, timesteps)"? or ground truth add noise directly like two number add in math?
