### ISSUE TITLE
I appreciate if you help me to test your project on CPU

### ISSUE THREAD

**Issue by keloniton** [levihsu/OOTDiffusion#114]
Hi. I have no CUDA. I want to test your project on CPU. These are the steps i follow:
git clone https://github.com/levihsu/OOTDiffusion
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
pip install -r requirements.txt
cd OOTDiffusion/run
python run_ootd.py --model_path <model-image-path> --cloth_path <cloth-image-path> --scale 2.0 --sample 4

But i get error for CUDA. How can i tell this to use CPU. Thank you.

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/issues/60#issuecomment-1965817521
