### ISSUE TITLE
run run_ootd and It took about 1 hour even though my graphics is 2060 Super!

### ISSUE THREAD

**Issue by imanbahmani** [levihsu/OOTDiffusion#115]
I run run_ootd and It took about 1 hour even though my graphics is 2060 Super!
my code for running this python command 
python run_ootd.py --model_path model.png --cloth_path cloth.jpg --scale 2.0 --sample 4

and cuda is active and avalable on my computer and my gpu count is 1 and gpu device is 0 

But renting the program takes so much time, how can I solve this problem?

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/issues/18#issuecomment-1958502250
