### ISSUE TITLE
Is realily you need random crop garment latent ?

### ISSUE THREAD

**Issue by Gzzgz** [levihsu/OOTDiffusion#120]
the paper this part:
<img width="973" alt="图片" src="https://github.com/levihsu/OOTDiffusion/assets/15968092/b034f3f1-c81e-49c8-962c-a32d9a2c9649">

![图片](https://github.com/levihsu/OOTDiffusion/assets/15968092/d3cc5551-6ba6-4671-9318-7f37d9ed9563)

In the inference time,the code not drop garment latent when uncond.

**Comment by levihsu** [comment]
Please read the paper more carefully. Dropout is performed **in the training process**. Thanks

**Comment by Gzzgz** [comment]
OK, this is here?
![图片](https://github.com/levihsu/OOTDiffusion/assets/15968092/fd08223f-5d83-4bd4-9bff-8caae9e0ade6)
