### ISSUE TITLE
Which Scheduler used in training process

### ISSUE THREAD

**Issue by liupengcnu** [levihsu/OOTDiffusion#124]
Hi, Dr Xu, which Scheduler you have used in the training process? is the DDPMScheduler? And how do you process the gt and noise  in the training process? only add directly or add with the noise_scheduler.add_noise?

**Comment by liupengcnu** [comment]
@T-Gu @ShineChen1024 Could you give me some guidance for the above questions? Thanks much

**Comment by thuc248997** [comment]
@liupengcnu Looks like there won't be training instructions for this repo :(
[link comment](https://www.reddit.com/r/StableDiffusion/comments/1bdn2of/ott_diffusion_open_source/)

**Comment by levihsu** [comment]
1. DDPMScheduler
2. noise_scheduler.add_noise
