### ISSUE TITLE
ONNX conversion

### ISSUE THREAD

**Issue by Shysto** [levihsu/OOTDiffusion#125]
Hi, excellent work!

I wanted to know if you were planning to support the exportation of your diffuser [`OotdPipeline`](https://github.com/levihsu/OOTDiffusion/blob/344112ad1c03c2af1cf7a1f07d689b18af4c175a/ootd/pipelines_ootd/pipeline_ootd.py#L78) to ONNX, or if you had some tips on how one could do this exportation?

I am referring to some conversion script like [the one for StableDiffusion ](https://github.com/huggingface/diffusers/blob/main/scripts/convert_stable_diffusion_checkpoint_to_onnx.py) from the diffusers library. Since your model architecture includes two U-Nets, I could not use this script out of the shell.

Thank you very much for any tips you can provide!

**Comment by levihsu** [comment]
Hi. Thanks for your question. Sorry that we don’t have such plans for now. Maybe you could try to modify the diffusers script for onnx conversion : )
