### ISSUE TITLE
garm img use clip image encode

### ISSUE THREAD

**Issue by kisstea** [levihsu/OOTDiffusion#126]
I don't find the code , to encode garment image use clip image encode as the input of gram unet in inference

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/blob/344112ad1c03c2af1cf7a1f07d689b18af4c175a/ootd/inference_ootd.py#L109

See **prompt_embeds** here

**Comment by kisstea** [comment]
ok, thx
