### ISSUE TITLE
Dropout in the outfitting

### ISSUE THREAD

**Issue by liupengcnu** [levihsu/OOTDiffusion#127]
Hi, I noticed that you used the dropout in the outfiting as show in the below image, I want tot know that the 10% dropout refers to 10% of each garment feature set to 0, or during the entire training process, 10% of the entire garment features are set to 0
![屏幕截图_4](https://github.com/levihsu/OOTDiffusion/assets/57616031/8ca366fa-35d0-4ec7-9acd-4eaea60fda56)

**Comment by levihsu** [comment]
![image](https://github.com/levihsu/OOTDiffusion/assets/33045876/adc4721b-baf2-4c9f-aa7b-4725bb1d41e6)
