### ISSUE TITLE
torch.cuda out of memory

### ISSUE THREAD

**Issue by Hankerlove** [levihsu/OOTDiffusion#128]
#### i wonder how can i solve it or the model really needs a higher-capability gpu to make inference

**Comment by levihsu** [comment]
Hi. It takes around 3 seconds and 6GB memory for 1 sample and 20 steps on our RTX 4090 GPU. Maybe a 6GB 3060 is not completely enough.

**Comment by bjbjbjbj** [comment]
> Hi. It takes around 3 seconds and 6GB memory for 1 sample and 20 steps on our RTX 4090 GPU. Maybe a 6GB 3060 is not completely enough.

I use 3060Ti 16G , same problem
