### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by xxxxboy** [levihsu/OOTDiffusion#129]
错误信息：
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 12.58it/s]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Traceback (most recent call last):
  File "F:\workpace\python\OOTDiffusion\run\gradio_ootd.py", line 22, in <module>
    ootd_model_hd = OOTDiffusionHD(0)
  File "F:\workpace\python\OOTDiffusion\ootd\inference_ootd_hd.py", line 71, in __init__
    self.image_encoder = CLIPVisionModelWithProjection.from_pretrained(VIT_PATH).to(self.gpu_id)
  File "D:\Anaconda3\envs\ootd2\lib\site-packages\transformers\modeling_utils.py", line 3371, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

文件下的没有问题，也注释了相关代码还有报错,
# openpose_model_dc = OpenPose(1)
# parsing_model_dc = Parsing(1)
# ootd_model_dc = OOTDiffusionDC(1)
openpose_model_dc = openpose_model_hd
parsing_model_dc = parsing_model_hd
ootd_model_dc = ootd_model_hd

**Comment by zijiwork** [comment]
什么原因
