### ISSUE TITLE
The value style of vae encode in the training process

### ISSUE THREAD

**Issue by liupengcnu** [levihsu/OOTDiffusion#132]
Hi, I noticed that you have used the "model()" type in vae encode as like this code "vae.encode().latent_dist.mode()", I want to know which value style of vae encode used in the training process, is "vae.encode().latent_dist.sample()" or "vae.encode().latent_dist.mode()"

**Comment by seungyonglee0802** [comment]
sry to interupt, anyway, what's the difference b/w `vae.encode().latent_dist.mode()` and `vae.encode().latent_dist.sample()`? Is this critical in training?

**Comment by kisstea** [comment]
> Hi, I noticed that you have used the "model()" type in vae encode as like this code "vae.encode().latent_dist.mode()", I want to know which value style of vae encode used in the training process, is "vae.encode().latent_dist.sample()" or "vae.encode().latent_dist.mode()"

use   "vae.encode().latent_dist.sample()"

**Comment by liupengcnu** [comment]
@levihsu which you used in training process? Is "vae.encode().latent_dist.sample()" or "vae.encode().latent_dist.mode()"?

**Comment by levihsu** [comment]
@liupengcnu Why are you so impolite and inconsiderate? Don't you see the help from @kisstea ?
https://github.com/levihsu/OOTDiffusion/issues/132#issuecomment-2012734381
We already answered so many questions of yours but you just keep disturbing us without any gratitude. This is the last time for us to reply to you. Thanks.
https://github.com/levihsu/OOTDiffusion/issues/119#issuecomment-2006556008
