### ISSUE TITLE
Using API

### ISSUE THREAD

**Issue by gundamp** [levihsu/OOTDiffusion#134]
How do I extract image after running the API using gradio_client?

It seems to return a temporary image path such as 
[{'image': '/tmp/gradio/c8ef09d7a7f335611efa026f92fe9998aba924ef/image.png', 'caption': None}]

**Comment by levihsu** [comment]
Hi. You could directly download it in the gradio api
![image](https://github.com/levihsu/OOTDiffusion/assets/33045876/3aa25971-3f24-445d-8f43-55b9148afe5c)
