### ISSUE TITLE
Request help with training

### ISSUE THREAD

**Issue by neuralchen** [levihsu/OOTDiffusion#135]
Recently, I reproduced the OOTD training code and trained it. 
I would like to ask how low the loss is considered normal. 
My loss was 1.2 at the beginning, and it has been hovering around 0.2 after more than 8,000 training steps. Is this normal?

The following pictures are the verification results of 2000 steps. It seems that it cannot learn the correct texture and style of clothes.
I would like to ask the author, is this normal?
Hope to get a reply, thanks!

![08432_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/078c3a64-3a52-452b-bac8-60ed958fde7b)
![08297_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/e40c6dd0-1170-4bbd-9ca0-baffa208ac51)

![06491_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/a89e0a48-712a-45ea-ac20-2492d281764e)
![04339_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/51eb9586-8ae3-4b09-ab66-e19b2bf30788)
![06753_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/835e237c-b95b-4df8-9ed4-042ab55bf85a)

![02204_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/d04e5aa5-c006-4fab-8ffa-fd9fee28c23d)
![02682_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/85646429-d8dd-48df-8d0a-2bf699172355)
![04240_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/573d683f-6209-4ada-a987-819b723e4eac)

![00683_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/60db1a11-ca77-4501-b6db-911e0f5161cd)
![01486_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/ff2d524d-172e-4dec-afad-0a535088814f)
![02023_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/3d0eb5aa-abdf-4fc5-b836-cc82afbf597c)
![05498_00_step_2000](https://github.com/levihsu/OOTDiffusion/assets/18433587/907118ac-db04-4af2-bc98-192bed1a8bd9)

**Comment by filippocastelli** [comment]
nice results! would you mind sharing the training code?

**Comment by yunjungleekt** [comment]
I also tried to write the training code, but when I run the training code with A100 40G, I get CUDA oom. What is the GPU memory you have or did you use any other alternative to reduce the memory? 

Thanks.

**Comment by failbetter77** [comment]
huggingface accelerate deepspeed allow to use only one model with deepspeed. 
(i think we have to use 1) garment unet, 2) vton unet ) 
How can i use with deepspeed in accelerate..?

**Comment by chenbinghui1** [comment]
> Models are trained in fp16

Hi, when training in fp16, have you encounterd the issue "Attempting to unscale FP16 gradients."?

**Comment by chenbinghui1** [comment]
> > > Models are trained in fp16
> > 
> > 
> > Hi, when training in fp16, have you encounterd the issue "Attempting to unscale FP16 gradients."?
> 
> Facing same issue

I solved this problem by：
[1] all the model are created by float32 data type:
`vae = AutoencoderKL.from_pretrained(
            VAE_PATH,
            subfolder="vae"
        )
unet_garm = UNetGarm2DConditionModel.from_pretrained(
            UNET_PATH,
            subfolder="unet_garm_train",
            use_safetensors=True
        )
unet_vton = UNetVton2DConditionModel.from_pretrained(
            UNET_PATH,
            subfolder="unet_vton_train",
            use_safetensors=True
  )`

[2] If you use accelarate.prepare(unet_garm, unet_vton); do not manually move them to GPU like `unet_garm.to(accelerator.device, dtype=weight_dtype)`

**Comment by chenbinghui1** [comment]
> This is not solution, this will train it in float32 then instead of float16

I don't know, but the official code in diffusers for training controlnet using the same strategy, you can have a look.

**Comment by i-amgeek** [comment]
@neuralchen Do you think results might be different because of using different training hyperparameters or data augmentation techniques?

**Comment by Aaron2117** [comment]
> The author must have trained more than 30,000 steps. The following is the result of my 30,000 steps: ![00035_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466215-cfde4cd7-e60d-4f03-be6e-bc461d8cdab5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjYyMTUtY2ZkZTRjZDctZTYwZC00ZjAzLWJlNmUtYmM0NjFkOGNkYWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMDBmYTA5NGQ1NzA4NGEzZmY5ODdkZDI0MjYzNDQzY2JkNjdkODc2YmNiNzUyYjJiNWRhOTE5YjYwOWFiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SKUz5sTUGHlevMJpH-t5ngZXNsPozT_kPOjB13nzaBM) ![00055_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466270-ccbdcd83-b5fd-4b1b-bc6a-a765d4858ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjYyNzAtY2NiZGNkODMtYjVmZC00YjFiLWJjNmEtYTc2NWQ0ODU4ZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OGYwZmMyNjVhYTY2ZjRmZGE2NjA1ZjcyOTFlNDdlZjllNDQ5NjRlNzgyOTMxNWQxNjhhN2FlMjFhMzdhMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6VMLGUp-jp9PuslOk0yYTm_iyjBKs1HPi8YdbyGRdY) ![00057_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466300-2b3f44c5-2d66-4859-80be-f1530cc2e7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjYzMDAtMmIzZjQ0YzUtMmQ2Ni00ODU5LTgwYmUtZjE1MzBjYzJlN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNzdjZDE1ZGM5OWNlZmU5ZTA4OGEzZWNjZDAyYjNkZTg5NTI1MjU3MTMzNmJmNzg5ZTQ1YzQ3N2NmOWNmNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sSAhmuY4yQPK4NRu0KamsyLndhQo6oGHjgfoldc-1fY) ![00064_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466329-ed7a66f2-e950-4553-b993-4961b582b15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjYzMjktZWQ3YTY2ZjItZTk1MC00NTUzLWI5OTMtNDk2MWI1ODJiMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDI3MmVkNzU4ZDRlZGQ4OGMzNDg2MGFjOWJhNjA3YzQ4MWZjYWI2YjI5MmQ2YTYxOThmMjdmZWUxNmRiYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4YmmwIk45S2RWjzhubHhX55bXvepV119-MOP-JPMP5o) ![00067_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466374-7e12be00-3349-4be0-bb78-08e7757b42c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjYzNzQtN2UxMmJlMDAtMzM0OS00YmUwLWJiNzgtMDhlNzc1N2I0MmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNmVjYzg1NDIyNjc2YzExODQ5MGYxNmM1NjU0ZDYxYTI1NDUxZDk2M2NhMDBjMjJhMDA1NzMyMmQ4M2JjMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ue5QngT7WFlOLcoV21fvyPuqz2PbcH9210tv6TeUiCY) ![00069_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466404-2c4955f5-a673-4515-b8db-79c7f5812a88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjY0MDQtMmM0OTU1ZjUtYTY3My00NTE1LWI4ZGItNzljN2Y1ODEyYTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YmM0MDQ0ZTRlZjdhZDUzNThjNmM2YjY0NmYwYTI5OWM0MWY0YTYwMDIzZmVmOTM3NjA3NTA3NWEyMzVhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bA_FmiwyfjXW0-NOmyTU0xRzxlqb9mIA0vnwfEfxRk) ![00071_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466455-285ef64a-ef75-44ae-a0c3-c8429d2a8c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjY0NTUtMjg1ZWY2NGEtZWY3NS00NGFlLWEwYzMtYzg0MjlkMmE4YzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YmEwZDA5ZjE0YzNkZjk1ZDRkNDhkODlhMDhjZDQzNjE0YTZjNzlmZmU4MTA3ZjgwZWQ3YTc4OTBmYWUyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_uUdGsjO6oxLV_Gil0wcP34Mq-IxEAflYO6MaWqwDA) ![00074_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466492-beb8070e-109d-4aea-8bf2-c7b42dfc579e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjY0OTItYmViODA3MGUtMTA5ZC00YWVhLThiZjItYzdiNDJkZmM1NzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZjliYzE2N2MxOTQ2MmU0ZjgxMmUwNjZhZWUyMTczZDI4OTgxMTUxYWE3OGUyY2UyZGQzNTIxOGE0ODI0MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kQK6g2pX9uEI0vnMxF1H4VZsNEzVfHVIIYG1u_3X2XQ) ![00006_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466524-ecc2e253-208b-4c7d-b086-5d18338f5365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjY1MjQtZWNjMmUyNTMtMjA4Yi00YzdkLWIwODYtNWQxODMzOGY1MzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYzNmYTQzOTkyZjY0ZjFhOTllNDJkYTgyZWExNzEyNTBkNWQxYjg3YTVjNjg5MzY4NjM5OWQ5ZjA2YTc4NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTVZbO7c-7ivR2lIvl4Kzrt3pXOfwUGb2k-jTk4GkKE) ![00017_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466540-c103262e-1718-4b03-b8ad-a6bb3c730afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjY1NDAtYzEwMzI2MmUtMTcxOC00YjAzLWI4YWQtYTZiYjNjNzMwYWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZWRkMWNkZjRkODI2NTVkNmNkYzMzNDc1NmU3NGY4MDAxNzJmMzg4YjNmOTU4MzcwZDJmNzg2MWVmNzFjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GHwIqW9X7oTgiM1gNFyk2jcT_2Cnwib3CADiRsjvnW0) ![00034_00_step_30000](https://private-user-images.githubusercontent.com/18433587/318466570-fe0a4f7a-c901-4eb8-a2e7-3e9af20a16ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc1NjksIm5iZiI6MTcxMjA2NzI2OSwicGF0aCI6Ii8xODQzMzU4Ny8zMTg0NjY1NzAtZmUwYTRmN2EtYzkwMS00ZWI4LWEyZTctM2U5YWYyMGExNmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MGJjNzdlNTEyOWNmNjU0ZGE5YWUxMDM4YzQ0NTkyZTAwMGFjZDkyMTViNGNkYzI5OTFmOGNiNDdkZWQzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VKgUk6NIxq4cyi4y3hjU3Zan8sHkCRpxz0OYOBD7yuo)

hello， @neuralchen i reproduced the OOTD training code and trained it, but i found my result is overfit with training in HDData. The results of the training set are good but the results of the test set are bad.
Maybe two unets training with a 10k training set does seem to overfit?
Have you ever encountered this problem?

**Comment by appleyang123** [comment]
Can anyone share the training code?

**Comment by Aaron2117** [comment]
@elenakovacic 300 epochs. i run inference on train set, the results is ok, but on test set is bad

**Comment by Aaron2117** [comment]
@neuralchen i train 300 epochs on VITON-HD data set. the image size is 512 x 384, and the loss is about 0.03.
can you tell me what  your final loss is at the end?

**Comment by levihsu** [comment]
@Aaron2117 300 epochs sounds too many. We only trained for 36000 steps (~42 epochs)

**Comment by levihsu** [comment]
> @Aaron2117 The results shown above are all from the test set. Our team believes that the training hyperparameters of ckpt released by the author are very different from those in the paper.

Could you tell us the reason? The training hyperparameters are completely same as those in our paper. Our model was trained for 36000 steps with the batch-size of 16 at 1024*768.

**Comment by appleyang123** [comment]
In VITON-HD dataset, I also faced the problem that the results on training data are good but no good on tested data.  Whether the open source model provided by the author is trained with the Test dataset?

> @Aaron2117 The results shown above are all from the test set. Our team believes that the training hyperparameters of ckpt released by the author are very different from those in the paper.

**Comment by levihsu** [comment]
> In VITON-HD dataset, I also faced the problem that the results on training data are good but no good on tested data. Whether the open source model provided by the author is trained with the Test dataset?
> 
> > @Aaron2117 The results shown above are all from the test set. Our team believes that the training hyperparameters of ckpt released by the author are very different from those in the paper.

Of course not. Don't you think it is ridiculous to train the model on the test data? This is a very severe accusation. The 30,000 step results of @neuralchen on test data look not bad already, though still worse than our 36,000 step checkpoints. And how to use an overfitting model for customized images beyond the dataset? Did you even see their results or try our demo? And did you carefully check the correctness of your code or training process? Your question is very impolite and unprofessional. We will release the training scripts later, or you can refer to others' implementation before that. Thank you.

**Comment by appleyang123** [comment]
Hi, I have checked the results. I guess that the public model is trained on resolution=768*1024, so infer the tested data in resolution=768*1024, it has a good result while it has inferior results with resolution=384*512
768*1024:
<img width="1349" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/790a3945-579e-4d11-84f5-c91d40a91aca">
<img width="1344" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/f48c451a-458e-4912-9c40-f550efaa39e8">
384*512:
<img width="1347" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/3fc9c958-f891-4b45-9cfb-97dcfe6b26ab">
<img width="1343" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/facdc9bb-5544-4d0e-9f7f-6b5315788875">


In my own experiment, I have the similar results. I have trained with resolution=384*512 in 14000 steps. The results in tested data with resolution=384*512 are much better than resolution=768*1024.
384*512:
<img width="1341" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/b377827b-04b2-42ec-8829-a25d32bd3f67">
<img width="1345" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/89baa895-69e1-4444-a06c-2529bff7db58">
768*1024:
<img width="1347" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/60386129-8fa4-45b9-bbf9-69ef09683d52">
<img width="1343" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/166299531/091fe09c-0490-4df1-9ce4-6d1538a67b02">

**Comment by Aaron2117** [comment]
> inferior
no, That's a serious accusation. I think it is our script that has errors rather than the author training on the test set.That's a pretty basic mistake

**Comment by puduliu** [comment]
> > [@neuralchen](https://github.com/neuralchen) Could you tell us the reason? The training hyperparameters are completely same as those in our paper. Our model was trained for 36000 steps with the batch-size of 16 at 1024*768.
> 
> Hey, how did you able to use batch-size of 16 at 1024*768 on single A100 80GB? It's only taking batch size of 2 with my script.
> 
> [@Aaron2117](https://github.com/Aaron2117) [@neuralchen](https://github.com/neuralchen) How much batch size you're using?

Hello, for every increase of 1 in batch size, the GPU memory increases a lot. Do you now know how the author achieved batch size = 16 and batch size = 64? Thank you very much
