### ISSUE TITLE
invalid load key, 'v' error

### ISSUE THREAD

**Issue by caption-dylan** [levihsu/OOTDiffusion#136]
**environment:**
![image](https://github.com/levihsu/OOTDiffusion/assets/14803721/ae6a4dc0-6431-4b4f-b4d9-5a70bcb9f44a)
**cmd:**
python run_ootd.py --model_path /home/OOTDiffusion/run/examples/model/model_1.png --cloth_path /home/OOTDiffusion/run/examples/garment/00055_00.jpg --model_type dc --category 2 --scale 2.0 --sample 4
**error:**
/opt/conda/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/opt/conda/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/opt/conda/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/opt/conda/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/OOTDiffusion/run/run_ootd.py", line 29, in <module>
    openpose_model = OpenPose(args.gpu_id)
  File "/home/OOTDiffusion/preprocess/openpose/run_openpose.py", line 33, in __init__
    self.preprocessor = OpenposeDetector()
  File "/home/OOTDiffusion/preprocess/openpose/annotator/openpose/__init__.py", line 63, in __init__
    self.body_estimation = Body(body_modelpath)
  File "/home/OOTDiffusion/preprocess/openpose/annotator/openpose/body.py", line 26, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by TrNgTinh** [comment]
I'm also having same problem

**Comment by ethankongee** [comment]
Same issue here

**Comment by ethankongee** [comment]
Ok I fixed it. You need git lfs and run `git lfs install` before you clone.

**Comment by TrNgTinh** [comment]
> Ok I fixed it. You need git lfs and run `git lfs install` before you clone.

That's right, if you don't use git lfs, it can only crawl files with a maximum size of about 100MB.
