### ISSUE TITLE
Gradio下是不是有点小问题

### ISSUE THREAD

**Issue by monyuan** [levihsu/OOTDiffusion#138]
4090的卡，跑了十三分钟，还是半身的

**Comment by monyuan** [comment]
的确是有问题，用命令跑，几秒出图，用Gradio web模式就得十几分钟

**Comment by levihsu** [comment]
请检查你的环境配置 我们自己的gradio demo都是几秒出图
https://huggingface.co/spaces/levihsu/OOTDiffusion
https://ootd.ibot.cn/

**Comment by monyuan** [comment]
的确是这样的，gradio demo13分钟，命令行几秒钟。环境配置如果有问题那么命令行应该也是十几分钟。对gradio 不熟，使用fastapi重写了，几秒出，gradio 就不行

**Comment by ccl-private** [comment]
我也遇到这个问题了
