### ISSUE TITLE
Not run in Windows

### ISSUE THREAD

**Issue by SevenAntares** [levihsu/OOTDiffusion#14]
Not run in Windows
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'

**Comment by Aruen24** [comment]
set CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'

**Comment by SevenAntares** [comment]
set CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'
conda deactivate
conda active ootd

some error
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'

**Comment by SevenAntares** [comment]
missing cuda libraries
