### ISSUE TITLE
Why return this err module 'torch._C' has no attribute '_cuda_setDevice' 这是为什么呢？

### ISSUE THREAD

**Issue by RKS112** [levihsu/OOTDiffusion#141]
(ootd) C:\Users\27214\Desktop\OOTDiffusion\run>python run_ootd.py --model_path C:\Users\27214\Desktop\OOTDiffusion\run\examples\model\02849_00.jpg --cloth_path C:\Users\27214\Desktop\OOTDiffusion\run\examples\garment\00055_00.jpg --scale 2.0 --sample 4
Traceback (most recent call last):
  File "C:\Users\27214\Desktop\OOTDiffusion\run\run_ootd.py", line 29, in <module>
    openpose_model = OpenPose(args.gpu_id)
  File "C:\Users\27214\Desktop\OOTDiffusion\preprocess\openpose\run_openpose.py", line 32, in __init__
    torch.cuda.set_device(gpu_id)
  File "C:\Users\27214\.conda\envs\ootd\lib\site-packages\torch\cuda\__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

vs and cuda i am already Install  but this err make me very sad dose some can help me  thank you very much

**Comment by soeminemi** [comment]
u may install the cpu version of torch

**Comment by levihsu** [comment]
Please follow our instruction to install the cuda version of pytorch

**Comment by Guoziiimakabaka** [comment]
you should use Linux but Window

**Comment by hanson-wen** [comment]
> you should use Linux but Window

can't be mac ？

**Comment by SaadMirzaBaig** [comment]
I don't see your instructions to install the cuda version of pytorch
