### ISSUE TITLE
请问运行结果为什么是马赛克服装？

### ISSUE THREAD

**Issue by Guoziiimakabaka** [levihsu/OOTDiffusion#143]
![90c228a30ca9946b0430373cc957157](https://github.com/levihsu/OOTDiffusion/assets/139534279/09f76e76-784d-40ae-8e75-fecc7c6c75a6)
请问为什么我的运行结果是这样的呢？

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/issues/82#issuecomment-1975955294
可以检查一下是不是checkpoints文件下载的有问题

**Comment by Guoziiimakabaka** [comment]
老师您好，这个是我的checkpoints文件，都是从您readme中提到的levihsu/OOTDiffusion at main (huggingface.co)这里下载的，请问是这些内容吗，还是还需要下载哪些东西？


惊鸿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "levihsu/OOTDiffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月2日(星期二) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [levihsu/OOTDiffusion] 请问运行结果为什么是马赛克服装？ (Issue #143)





 
#82 (comment)
 可以检查一下是不是checkpoints文件下载的有问题

**Comment by Guoziiimakabaka** [comment]
刚刚按照您的方法检查了一下，发现确实是checkpoints的问题，我一开始误以为所有diffusion_pytorch_model文件都是一样的，非常感谢！


惊鸿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "levihsu/OOTDiffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月2日(星期二) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [levihsu/OOTDiffusion] 请问运行结果为什么是马赛克服装？ (Issue #143)





 
#82 (comment)
 可以检查一下是不是checkpoints文件下载的有问题
