### ISSUE TITLE
怎么运行这个项目呢

### ISSUE THREAD

**Issue by eAtSomecoconut** [levihsu/OOTDiffusion#151]
我下载了pycharm叶配了pytorch还是很多报错，请问大家是用什么方法运行的呢

**Comment by levihsu** [comment]
仅安装Pytorch是远远不够的 请参考readme配置环境

**Comment by chuan1127** [comment]
我运作这个项目在docker中，但是每次都有需要重新下载模型，怎么将数据持久化

**Comment by taajason** [comment]
`OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ../checkpoints/ootd is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.`
按照readme中的步骤，提示上述报错，请问是什么原因，checkpoints/ootd目录下，确实没有config.json文件
<img width="293" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/34680966/4c11c11f-06cd-44b7-85be-23fbe39d3733">
请问该如何解决？

> 仅安装Pytorch是远远不够的 请参考readme配置环境

**Comment by levihsu** [comment]
> `OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ../checkpoints/ootd is not the path to a directory containing a config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.` 按照readme中的步骤，提示上述报错，请问是什么原因，checkpoints/ootd目录下，确实没有config.json文件 <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/34680966/340517209-4c11c11f-06cd-44b7-85be-23fbe39d3733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzkyMTgsIm5iZiI6MTcxODY3ODkxOCwicGF0aCI6Ii8zNDY4MDk2Ni8zNDA1MTcyMDktNGMxMWMxMWYtMDZjZC00NGI3LTg1YmUtMjNmYmUzOWQzNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAyNDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ODRkODU5Yjg3NTA3ZjQ2MzU4MDhlYWJlYjdmYjY5MzgxNzRjYzE1MDM3MWQxNDkwMTk4ZWYxYTUzY2I0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vaYn11_WG2ik-Lg7K0BAFj2yDREw59Iq7oqspWMK3vU"> 请问该如何解决？
> 
> > 仅安装Pytorch是远远不够的 请参考readme配置环境

这个之前也有人遇到过 是报错有误导性 其实是子文件夹内有多个config.json 请再检查一下文件名
