### ISSUE TITLE
Downloading: "https://huggingface.co/lllyasviel/Annotators/resolve/main/body_pose_model.pth"  显示没有这个文件

### ISSUE THREAD

**Issue by minmin0516** [levihsu/OOTDiffusion#154]
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>
请问我在哪里能够再下载这个模型呢 hf-mirror中也没找到

**Comment by levihsu** [comment]
https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints/openpose/ckpts
