### ISSUE TITLE
您是指“ https://ootd.ibot.cn/”这个网址重新启动吗，不行，我换台电脑都不行，

### ISSUE THREAD

**Issue by psksiu** [levihsu/OOTDiffusion#155]
前几天突然能上，但是今天不能上，
![微信图片_20240411111405](https://github.com/levihsu/OOTDiffusion/assets/80295321/53603b32-8acd-4386-9f86-d11da3aed7ed)

**Comment by levihsu** [comment]
刚刚又重启了 这个网址使用的是我们本地服务器，不定期需要维护之类的不建议长期依赖 常用的话还是建议使用Huggingface space或者自己本地部署哈

**Comment by psksiu** [comment]
好的谢谢大佬
