### ISSUE TITLE
本地跑的时候 ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\embeddings.py)

### ISSUE THREAD

**Issue by psksiu** [levihsu/OOTDiffusion#156]
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\embeddings.py)请问这个怎么解决

**Comment by ethankongee** [comment]
版本問題。你可以用`pip install -r requirements.txt`

diffusers v24有這個class。最新的v27不知道他們把這個class放到哪了。

**Comment by psksiu** [comment]
好的谢谢大佬
