### ISSUE TITLE
Any rough estimate on how much it would cost to train it ?

### ISSUE THREAD

**Issue by nitesh-dubey** [levihsu/OOTDiffusion#157]
@levihsu

**Comment by levihsu** [comment]
At 512*384, it takes ~75 hours for 36000 steps with batch-size of 64 on a single A100 GPU (80 GB)

**Comment by nitesh-dubey** [comment]
I see.. thanks!
What's the best cloud provider for A100  ?

I checked GCP provides it for $4/hr

**Comment by levihsu** [comment]
Sorry I don't know... We use our own servers.

**Comment by nitesh-dubey** [comment]
I see... thanks !

By the way how much data are you using ?
Are you scraping it from somewhere ?

**Comment by levihsu** [comment]
Please refer to [our paper](https://arxiv.org/abs/2403.01779) for those details : )
