### ISSUE TITLE
There is a problem with the program or documentation.

### ISSUE THREAD

**Issue by hodachi-axcxept** [levihsu/OOTDiffusion#16]
Should update the following.

1. The following files are required in checkpoints/humanparsing
exp-schp-201908301523-atr.pth
exp-schp-201908261155-lip.pth
exp-schp-201908270938-pascal-person-part.pth

2. Program modification of degradations.py is required
・Instead of from torchvision.transforms.functional_tensor import rgb_to_grayscale
・from torchvision.transforms.functional import rgb_to_grayscale
Otherwise, Module not found will occur.

**Comment by T-Gu** [comment]
Please refer to our latest environment requirements. 
[https://github.com/levihsu/OOTDiffusion/blob/main/requirements.txt](url)
