### ISSUE TITLE
while trainning , Is it correct that these images are generated halfway through the learning...?

### ISSUE THREAD

**Issue by edith-wq** [levihsu/OOTDiffusion#166]
![image](https://github.com/levihsu/OOTDiffusion/assets/117714440/b7572765-eb5d-4223-9427-99c94e5e3af3)

can you guess, where is it wrong? 

## train scheduler
train scheduler :
{
"_class_name": "PNDMScheduler",
"_diffusers_version": "0.6.0",
"beta_end": 0.012,
"beta_schedule": "scaled_linear",
"beta_start": 0.00085,
"num_train_timesteps": 1000,
"set_alpha_to_one": false,
"skip_prk_steps": true,
"steps_offset": 1,
"trained_betas": null,
"clip_sample": false
}

## sd1.5 config for garm_unet and vton_unet : (copy from runwayml, sd1.5 unet config) 
{
  "_class_name": "UNet2DConditionModel",
  "_diffusers_version": "0.6.0",
  "act_fn": "silu",
  "attention_head_dim": 8,
  "block_out_channels": [
    320,
    640,
    1280,
    1280
  ],
  "center_input_sample": false,
  "cross_attention_dim": 768,
  "down_block_types": [
    "CrossAttnDownBlock2D",
    "CrossAttnDownBlock2D",
    "CrossAttnDownBlock2D",
    "DownBlock2D"
  ],
  "downsample_padding": 1,
  "flip_sin_to_cos": true,
  "freq_shift": 0,
  "in_channels": 4,
  "layers_per_block": 2,
  "mid_block_scale_factor": 1,
  "norm_eps": 1e-05,
  "norm_num_groups": 32,
  "out_channels": 4,
  "sample_size": 64,
  "up_block_types": [
    "UpBlock2D",
    "CrossAttnUpBlock2D",
    "CrossAttnUpBlock2D",
    "CrossAttnUpBlock2D"
  ]
}

**Comment by i-amgeek** [comment]
Feels very undertrained. Try training more and testing on more images.

**Comment by Thethreebodyproblem** [comment]
why this low diffuser version?

**Comment by edith-wq** [comment]
> why this low diffuser version?

 just copy from the diffusers..
Next time i will upgrade the version.
