### ISSUE TITLE
cuda out of memory even though there is enough free 

### ISSUE THREAD

**Issue by DenisSud** [levihsu/OOTDiffusion#167]
when trying to python run_ootd.py i get this error: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB. GPU 0 has a total capacty of 4.00 GiB of which 2.80 GiB is free. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated.
The error shows that the amount of free memory is more than enough but it's a "OutOfMemoryError"? I haven't found any solutions to this problem online in any similar use cases.

**Comment by levihsu** [comment]
4GB is not enough for inference
