### ISSUE TITLE
where can i download the ootd_dc model?

### ISSUE THREAD

**Issue by frankchieng** [levihsu/OOTDiffusion#17]
it seems like only the ootd_hd upper body model has been released,when and how can i get the full body ootd_dc model?i appreciate for your hard work

**Comment by pvbang** [comment]
duplicated ootd_hd in /checkpoints/ootd/ and rename to ootd_dc

Like this:
![image](https://github.com/levihsu/OOTDiffusion/assets/89725712/a2da9c67-fa81-449b-8641-79cd579825c1)

**Comment by Nick1211** [comment]
I meet the same issue? where we can download the "OOTDiffusion/checkpoints/ootd/ootd_dc"

**Comment by levihsu** [comment]
The ootd_dc model is available now. Thanks for your patience : )

**Comment by frankchieng** [comment]
> The ootd_dc model is available now. Thanks for your patience : )

when i run the gradio_ootd.py, it raise error as below:
    raise ValueError(
ValueError: Cannot load ../checkpoints/ootd/ootd_dc/checkpoint-36000 because conv_in.weight expected shape tensor(..., device='meta', size=(320, 4, 3, 3)), but got torch.Size([320, 8, 3, 3]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

i tried to modify the ootd/inference_ootd_dc.py with

        unet_garm = UNetGarm2DConditionModel.from_pretrained(
              UNET_PATH,
              subfolder="unet_garm",
              torch_dtype=torch.float16,
              use_safetensors=True，
              low_cpu_mem_usage=False，
              ignore_mismatched_sizes=True
          )
          unet_vton = UNetVton2DConditionModel.from_pretrained(
              UNET_PATH,
              subfolder="unet_vton",
              torch_dtype=torch.float16,
              use_safetensors=True,
              low_cpu_mem_usage=False，
              ignore_mismatched_sizes=True
          )

then i can run gradio successfully,
but the Full-body generation with DC model renders quality is so badly, any clue how i can solve this issue?

**Comment by 1PD-IS-NO-1** [comment]
Please share the code or instruction to download ootd_dc.ckpt.
