### ISSUE TITLE
请问三张4090（24GB）可以对模型进行训练么？

### ISSUE THREAD

**Issue by xuyu666** [levihsu/OOTDiffusion#176]
作者您好：
我准备对您的模型进行训练，但我没有A100训练卡，请问我用3张4090卡可以进行训练么？若可以，如何设置Accelerate等相关参数呢，麻烦您教教我~

**Comment by levihsu** [comment]
按照我们的配置24G即使batch-size=1也是不行的 除非多加一些节省显存的tricks，例如8bit adam等

**Comment by xuyu666** [comment]
那如果按照你们的配置，需要多大显存的显卡~（我还有几张A40--44GB）

**Comment by levihsu** [comment]
我们用的是80GB A100，40GB的话batch-size=1或许可以跑得起来

**Comment by xuyu666** [comment]
好的，谢谢你~
