### ISSUE TITLE
#Question#  Is it normal that the process is so slow?

### ISSUE THREAD

**Issue by SevenAntares** [levihsu/OOTDiffusion#18]
Is it normal that the process is so slow? 16 minutes in RTX 2060 
4 samples
Windows 10

![image](https://github.com/levihsu/OOTDiffusion/assets/12645452/499c6c24-f29c-4f09-bd08-404aab16c7a8)

**Comment by levihsu** [comment]
Maybe the performance of RTX 2060 is not enough. It takes ~3s for 1 sample on my RTX 4090
![image](https://github.com/levihsu/OOTDiffusion/assets/33045876/5ae7f48f-c161-4281-b2dc-b5b96264b654)

**Comment by liuyifeng593** [comment]
Hello, please tell me how to deploy this project. According to the author's documentation, I did not deploy successfully.

**Comment by cleghom** [comment]
Tesla p40, > 1 hour:
![image](https://github.com/levihsu/OOTDiffusion/assets/12879946/08dbe427-a415-40bb-a576-a8d468ce8ebe)

**Comment by ccl-private** [comment]
3090 costs 25s, is it normal?

**Comment by ggjge** [comment]
> Tesla p40, > 1 hour: ![image](https://github.com/levihsu/OOTDiffusion/assets/12879946/08dbe427-a415-40bb-a576-a8d468ce8ebe)
> 
> while A100, ~ 15s ![image](https://github.com/levihsu/OOTDiffusion/assets/12879946/0f09e442-2430-49fd-bc26-14d3d8e53a96)

can you show me your cammand? My A800 cost 16min for each step and takes about 5 hours for each pic
