### ISSUE TITLE
此项目是否只能使用gpu版本的torch？

### ISSUE THREAD

**Issue by caicaicaibeiqie** [levihsu/OOTDiffusion#196]
如题，我在本地运行python run_ootd.py --model_path D:\work\testimg\PPtest\model1.jpg --cloth_path D:\work\testimg\PPtest\pp1.jpg --model_type dc --category 2 --scale 2.0 --sample 4

**Comment by caicaicaibeiqie** [comment]
openpose_model = OpenPose(args.gpu_id)
  File "D:\work\cangku\wearclothbyOOTD\OOTDiffusion-main\preprocess\openpose\run_openpose.py", line 32, in __init__
    torch.cuda.set_device(gpu_id)
  File "D:\tools\py39\lib\site-packages\torch\cuda\__init__.py", line 408, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
以上是运行时报的错误。 我本地使用的是cpu版本的pytorch。 没有选择GPU设备相关的方法。
如何利用现有的cpu版torch运行项目？

**Comment by levihsu** [comment]
是的 只支持GPU
