### ISSUE TITLE
节点爆红 不能用了 

### ISSUE THREAD

**Issue by vaan89** [levihsu/OOTDiffusion#197]
今天打开后发现节点爆红 修复重装都没用 怎么解决

**Comment by levihsu** [comment]
？不明白你指的是什么

**Comment by vaan89** [comment]
节点失效了 
修复不了 重装也是
你的节点不兼容最新版本的comfyui

发自我的iPhone

**Comment by levihsu** [comment]
Comfyui的问题请不要在这里问 不是官方内容
