### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by shirubei** [levihsu/OOTDiffusion#2]
找不到config文件

(Outfit) D:\Python310\Outfit\OOTDiffusion\run>python run_ootd.py --model_path examples\model --cloth_path examples\garment --scale 2.0 --sample 4
Traceback (most recent call last):
  File "D:\Python310\Outfit\OOTDiffusion\run\run_ootd.py", line 9, in <module>
    from preprocess.openpose.run_openpose import OpenPose
  File "D:\Python310\Outfit\OOTDiffusion\preprocess\openpose\run_openpose.py", line 3, in <module>
    import config
ModuleNotFoundError: No module named 'config'

**Comment by levihsu** [comment]
Model checkpoints have not been released yet. I will release 1024*768 resolution checkpoints trained on VITON-HD soon.

**Comment by jeffreyrobeson** [comment]
用那个config.json？没找到？

**Comment by jeffreyrobeson** [comment]
问题怎么解决的？
