### ISSUE TITLE
Great work! How to call the checkpoints in script? 

### ISSUE THREAD

**Issue by WilTay1** [levihsu/OOTDiffusion#20]
After I download these checkpoints, where should I put them and how to call them in the script? Thanks!
<img width="470" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/133484736/9883183d-bccf-4195-a6d8-582001a2e34f">

**Comment by levihsu** [comment]
Just copy ***checkpoints*** folder into root directory and run run_ootd.py
