### ISSUE TITLE
Please tell me where is the config.json file?

### ISSUE THREAD

**Issue by wuhuiduan** [levihsu/OOTDiffusion#204]
I encountered an error "OSError: Error no file named config.json found in directory ../checkpoints/ootd." But I cannot find a config.json in hugging face 
[checkpoints](https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints). Thanks!

<img width="753" alt="微信图片_20240723114147" src="https://github.com/user-attachments/assets/a9b6b472-5635-49f5-8f01-984edc650e12">

**Comment by wuhuiduan** [comment]
Oh, I have find out my mistakes. The config.json files locate in checkpoints\ootd\ootd_dc\checkpoint-36000\unet_garm, after I corrected the name, the project worked well.

**Comment by nitinmukesh** [comment]
@wuhuiduan 

Please could you help. I am getting the same error.

![image](https://github.com/user-attachments/assets/285a5264-0acd-47ba-8943-10f1bd5ddcab)
