### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by jeffreyrobeson** [levihsu/OOTDiffusion#22]
(ootd) E:\software\OOTDiffusion\run>python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model --cloth_path E:\software\OOTDiffusion\run\examples\garment --scale 2.0 --sample 4
Traceback (most recent call last):
  File "E:\software\OOTDiffusion\run\run_ootd.py", line 9, in <module>
    from preprocess.openpose.run_openpose import OpenPose
  File "E:\software\OOTDiffusion\preprocess\openpose\run_openpose.py", line 3, in <module>
    import config
ModuleNotFoundError: No module named 'config'

**Comment by jeffreyrobeson** [comment]
已经解决

**Comment by Zhangyue168** [comment]
请问大佬怎么解决的？

**Comment by levihsu** [comment]
> 请问大佬怎么解决的？

pip install config
