### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3'

### ISSUE THREAD

**Issue by jeffreyrobeson** [levihsu/OOTDiffusion#24]
(ootd) E:\software\OOTDiffusion\run>python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model\ --cloth_path E:\software\OOTDiffusion\run\examples\garment\ --scale 2.0 --sample 4
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3'
C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。

**Comment by jeffreyrobeson** [comment]
CUDA是要降到11.7吗？

**Comment by levihsu** [comment]
嗯我们用的是11.7

**Comment by jeffreyrobeson** [comment]
(ootd) E:\software\OOTDiffusion\run>python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model\ --cloth_path E:\software\OOTDiffusion\run\examples\garment\ --scale 2.0 --sample 4
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')

**Comment by jeffreyrobeson** [comment]
降到11.7也不行

**Comment by jeffreyrobeson** [comment]
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

**Comment by jeffreyrobeson** [comment]
(ootd) E:\software\OOTDiffusion\run>python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model\ --cloth_path E:\software\OOTDiffusion\run\examples\garment\ --scale 2.0 --sample 4
Traceback (most recent call last):
  File "E:\software\OOTDiffusion\run\run_ootd.py", line 10, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "E:\software\OOTDiffusion\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "E:\software\OOTDiffusion\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1800, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1887, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib", "x64")}')
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2407, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

(ootd) E:\software\OOTDiffusion\run>

**Comment by jeffreyrobeson** [comment]
把cl.exe路径加到系统变量里还是报错

**Comment by Rinne61** [comment]
> 路径要直接指定到文件，比如--model_path OOTDiffusion\run\examples\model\test.jpg

**Comment by jeffreyrobeson** [comment]
(ootd) PS E:\software\OOTDiffusion\run> python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model\model_1.png --cloth_path E:\software\OOTDiffusion\run\examples\garment\02305_00.jpg --scale 2.0 --sample 4
C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Error checking compiler version for cl: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "E:\software\OOTDiffusion\run\run_ootd.py", line 10, in <module>
    from preprocess.humanparsing.aigc_run_parsing import Parsing
  File "E:\software\OOTDiffusion\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from parsing_api import load_atr_model, load_lip_model, inference
  File "E:\software\OOTDiffusion\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    import networks
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "E:\software\OOTDiffusion\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\software\OOTDiffusion\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1800, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1887, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib", "x64")}')
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2407, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
(ootd) PS E:\software\OOTDiffusion\run>

**Comment by jeffreyrobeson** [comment]
还是出错

**Comment by guahunyo** [comment]
![RL7XNA2$7UQZT_@X@4F}@D7](https://github.com/levihsu/OOTDiffusion/assets/18573180/0f5f8d5b-527b-4b2d-8b00-5d8cf4a7b6f9)
我也是12.3也不行
![I4O%XCI0H_X1XTE11~9N39I](https://github.com/levihsu/OOTDiffusion/assets/18573180/ee37effd-c598-4c17-a21d-f18f09c0db48)

**Comment by nkTmmT** [comment]
> ![RL7XNA2$7UQZT_@X@4F}@D7](https://private-user-images.githubusercontent.com/18573180/307040741-0f5f8d5b-527b-4b2d-8b00-5d8cf4a7b6f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDkzNTMsIm5iZiI6MTcwODY0OTA1MywicGF0aCI6Ii8xODU3MzE4MC8zMDcwNDA3NDEtMGY1ZjhkNWItNTI3Yi00YjJkLThiMDAtNWQ4Y2Y0YTdiNmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAwNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkODAwYjgwYjNiNmJlMWFhY2JlOGM5NGUyOGFlYmRjZjhiNTc3NjQ0Yjc1YTZhZDUyODZhODhjMzEwZjFkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jReLFGcQ71hWxdl5lI26I1S9R6R04id_-Y0mhmHr9H0) 我也是12.3也不行 ![I4O%XCI0H_X1XTE11~9N39I](https://private-user-images.githubusercontent.com/18573180/307041039-ee37effd-c598-4c17-a21d-f18f09c0db48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDkzNTMsIm5iZiI6MTcwODY0OTA1MywicGF0aCI6Ii8xODU3MzE4MC8zMDcwNDEwMzktZWUzN2VmZmQtYzU5OC00YzE3LWEyMWQtZjE4ZjA5YzBkYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAwNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzFjMDY5YzA2YTU1ODI2Y2YxZjQ3MjFhNGE3NjE2YjAxODhhMDA3ZDFmNjdiODJmMTVkYzM2Mzk3NTk1OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t_42_yQU8nJXNgDAbkTyK52gWX2pp7wRYfTQNKLPPVM)

把graido_ootd.py里面的29, 30, 31的1改成0
![image](https://github.com/levihsu/OOTDiffusion/assets/33121696/bcf6d812-229a-4c52-90e9-bf41bc24c0d3)

**Comment by nkTmmT** [comment]
> CUDA_HOME

环境变量里有配置CUDA_HOME 吗, 配置好了后重启命令行试试

**Comment by guahunyo** [comment]
> > ![RL7XNA2$7UQZT_@X@4F}@D7](https://private-user-images.githubusercontent.com/18573180/307040741-0f5f8d5b-527b-4b2d-8b00-5d8cf4a7b6f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDkzNTMsIm5iZiI6MTcwODY0OTA1MywicGF0aCI6Ii8xODU3MzE4MC8zMDcwNDA3NDEtMGY1ZjhkNWItNTI3Yi00YjJkLThiMDAtNWQ4Y2Y0YTdiNmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAwNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkODAwYjgwYjNiNmJlMWFhY2JlOGM5NGUyOGFlYmRjZjhiNTc3NjQ0Yjc1YTZhZDUyODZhODhjMzEwZjFkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jReLFGcQ71hWxdl5lI26I1S9R6R04id_-Y0mhmHr9H0) 我也是12.3也不行 ![I4O%XCI0H_X1XTE11~9N39I](https://private-user-images.githubusercontent.com/18573180/307041039-ee37effd-c598-4c17-a21d-f18f09c0db48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDkzNTMsIm5iZiI6MTcwODY0OTA1MywicGF0aCI6Ii8xODU3MzE4MC8zMDcwNDEwMzktZWUzN2VmZmQtYzU5OC00YzE3LWEyMWQtZjE4ZjA5YzBkYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAwNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzFjMDY5YzA2YTU1ODI2Y2YxZjQ3MjFhNGE3NjE2YjAxODhhMDA3ZDFmNjdiODJmMTVkYzM2Mzk3NTk1OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t_42_yQU8nJXNgDAbkTyK52gWX2pp7wRYfTQNKLPPVM)
> 
> 把graido_ootd.py里面的29, 30, 31的1改成0 ![image](https://private-user-images.githubusercontent.com/33121696/307197234-bcf6d812-229a-4c52-90e9-bf41bc24c0d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjQ5MjUsIm5iZiI6MTcwODY2NDYyNSwicGF0aCI6Ii8zMzEyMTY5Ni8zMDcxOTcyMzQtYmNmNmQ4MTItMjI5YS00YzUyLTkwZTktYmY0MWJjMjRjMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA1MDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNDJhZmIwOGRmMTcxODU0MjMxN2NiNmMwYTIzNTBlN2VlNmEyZTIxZDc5ZWUwM2Q2YTdiMjBiZTIzMzFiOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssiFxE9Kv9yqdyH-LyKMq9AWcVSdQYfyNEgnWqFMx6g)

现在跑起来了 不过全身的好像还有点问题

**Comment by jeffreyrobeson** [comment]
我的跑不起来，帮忙看看呀

**Comment by jin1wang** [comment]
我也是找不到，然后直接加了cuda就可以
pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 numpy==1.24.4 scipy==1.10.1 scikit-image==0.21.0 opencv-python==4.7.0.72 pillow==9.4.0 diffusers==0.24.0 transformers==4.36.2 accelerate==0.26.1 matplotlib==3.7.4 tqdm==4.64.1 gradio==4.16.0 config==0.5.1 einops==0.7.0 ninja==1.10.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by T-Gu** [comment]
@jeffreyrobeson 可以试下安装最新的环境，目前还没有在Windows测试
[https://github.com/levihsu/OOTDiffusion/blob/main/requirements.txt](url)
