### ISSUE TITLE
No module named 'torch._custom_ops'

### ISSUE THREAD

**Issue by jeffreyrobeson** [levihsu/OOTDiffusion#30]
(ootd) E:\software\OOTDiffusion\run>python run_ootd.py --model_path E:\software\OOTDiffusion\run\examples\model\model_1.png --cloth_path E:\software\OOTDiffusion\run\examples\garment\02305_00.jpg --scale 2.0 --sample 4
Traceback (most recent call last):
  File "E:\software\OOTDiffusion\run\run_ootd.py", line 9, in <module>
    from preprocess.openpose.run_openpose import OpenPose
  File "E:\software\OOTDiffusion\preprocess\openpose\run_openpose.py", line 20, in <module>
    from preprocess.openpose.annotator.openpose import OpenposeDetector
  File "E:\software\OOTDiffusion\preprocess\openpose\annotator\openpose\__init__.py", line 15, in <module>
    from .body import Body
  File "E:\software\OOTDiffusion\preprocess\openpose\annotator\openpose\body.py", line 14, in <module>
    from torchvision import transforms
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\Administrator\pinokio\bin\miniconda\envs\ootd\lib\site-packages\torchvision\_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'

(ootd) E:\software\OOTDiffusion\run>

**Comment by jeffreyrobeson** [comment]
How can I solve this problem?

**Comment by jeffreyrobeson** [comment]
pip uninstall torch
pip uninstall torchvision
conda clean -a
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
python -c "import torch; print(torch.cuda.is_available())"
nvcc --version
python -m torch.utils.collect_env

**Comment by jeffreyrobeson** [comment]
The problem has been solved

**Comment by 508135669** [comment]
![1710729798369](https://github.com/levihsu/OOTDiffusion/assets/137295423/3c94e032-3865-459b-8be0-ac077da528bb)
I want to know that “ No module named 'torch._custom_ops' ”  this problem,how should be solved

**Comment by chilljudaoren** [comment]
> pip uninstall torch pip uninstall torchvision conda clean -a pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia python -c "import torch; print(torch.cuda.is_available())" nvcc --version python -m torch.utils.collect_env

May I ask if cuda=11.6 is OK?

**Comment by chilljudaoren** [comment]
> ![1710729798369](https://private-user-images.githubusercontent.com/137295423/313533917-3c94e032-3865-459b-8be0-ac077da528bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTAwMDUsIm5iZiI6MTcxMDgwOTcwNSwicGF0aCI6Ii8xMzcyOTU0MjMvMzEzNTMzOTE3LTNjOTRlMDMyLTM4NjUtNDU5Yi04YmUwLWFjMDc3ZGE1MjhiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMDU1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjc1YTMzOTlhMDg3MGYwNDk1Mjc5NjNhNWYxODEyMzdkMDQxZWZiMmI0YzkzMWU3YjVlODQ0YzkzMDJlNTQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KxWzWnZAWuvZzFiFicIxDhXN8pN19q7oO02JiFjDpvI) I want to know that “ No module named 'torch._custom_ops' ” this problem,how should be solved

You can follow the author's method above.
