### ISSUE TITLE
Congrats for your work and..

### ISSUE THREAD

**Issue by juanmarin96** [levihsu/OOTDiffusion#4]
This is great job, do you have plans to release model's checkpoints soon?

**Comment by narendraadloid** [comment]
yeah please let us know

**Comment by levihsu** [comment]
Thanks for your question. The 1024*768 resolution checkpoints trained on VITON-HD will be released soon.

**Comment by levihsu** [comment]
Our model checkpoints trained on VITON-HD (768 * 1024) has been released. Thanks for your patience.
