### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by lynn123123** [levihsu/OOTDiffusion#42]
```
Traceback (most recent call last):
  File "/mnt/e/project/80297283/OOTDiffusion/run/gradio_ootd.py", line 29, in <module>
    openpose_model_dc = OpenPose(1)
  File "/mnt/e/project/80297283/OOTDiffusion/preprocess/openpose/run_openpose.py", line 32, in __init__
    torch.cuda.set_device(gpu_id)
  File "/home/pub_gpu/anaconda3/envs/ootd/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

how do i fix it?  
ps: who run the gradio demo successfully?

**Comment by lynn123123** [comment]
i fix it, 
```
openpose_model_hd = OpenPose(0)
parsing_model_hd = Parsing(0)
ootd_model_hd = OOTDiffusionHD(0)

openpose_model_dc = OpenPose(1)
parsing_model_dc = Parsing(1)
ootd_model_dc = OOTDiffusionDC(1)
```
the code need 2 gpus ， but i have one,
 so  i  change code like this 
```
openpose_model_hd = OpenPose(0)
parsing_model_hd = Parsing(0)
ootd_model_hd = OOTDiffusionHD(0)

openpose_model_dc =openpose_model_hd
parsing_model_dc = parsing_model_hd 
ootd_model_dc = ootd_model_hd 
```

finally ,i run gradio demo successfully

**Comment by jmplay** [comment]
> i fix it,
> 
> ```
> openpose_model_hd = OpenPose(0)
> parsing_model_hd = Parsing(0)
> ootd_model_hd = OOTDiffusionHD(0)
> 
> openpose_model_dc = OpenPose(1)
> parsing_model_dc = Parsing(1)
> ootd_model_dc = OOTDiffusionDC(1)
> ```
> 
> the code need 2 gpus ， but i have one, so i change code like this
> 
> ```
> openpose_model_hd = OpenPose(0)
> parsing_model_hd = Parsing(0)
> ootd_model_hd = OOTDiffusionHD(0)
> 
> openpose_model_dc =openpose_model_hd
> parsing_model_dc = parsing_model_hd 
> ootd_model_dc = ootd_model_hd 
> ```
> 
> finally ,i run gradio demo successfully

Thank you, I changed run\gradio_ootd.py in line 25 as you suggest, It works OK.
