### ISSUE TITLE
running gradio_ootd.py, cuda error

### ISSUE THREAD

**Issue by TigerHH6866** [levihsu/OOTDiffusion#43]
(ootd) root@autodl-container-cf29119c3c-0ecee78c:~/autodl-tmp/OOTDiffusion/run# python gradio_ootd.py
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.08it/s]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 11.18it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/OOTDiffusion/run/gradio_ootd.py", line 31, in <module>
    ootd_model_dc = OOTDiffusionDC(1)
  File "/root/autodl-tmp/OOTDiffusion/ootd/inference_ootd_dc.py", line 74, in __init__
    ).to(self.gpu_id)
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 864, in to
    module.to(device, dtype)
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by levihsu** [comment]
Our gradio demo requires 2 GPUs. Since ootd_dc checkpoints are not released yet, you may simply comment the code involving ootd_dc for now.

**Comment by TigerHH6866** [comment]
> Our gradio demo requires 2 GPUs. Since ootd_dc checkpoints are not released yet, you may simply comment the code involving ootd_dc for now.

o thx

**Comment by karthikg-09** [comment]
> Our gradio demo requires 2 GPUs. Since ootd_dc checkpoints are not released yet, you may simply comment the code involving ootd_dc for now.

Any ETA for ootd_dc?

**Comment by levihsu** [comment]
> > Our gradio demo requires 2 GPUs. Since ootd_dc checkpoints are not released yet, you may simply comment the code involving ootd_dc for now.
> 
> Any ETA for ootd_dc?

Available now.
