### ISSUE TITLE
![image](https://github.com/levihsu/OOTDiffusion/assets/33121696/63351d0e-1f47-40fb-9bfe-9a1cfa4182e2)

### ISSUE THREAD

**Issue by xiyuxiaoxiao** [levihsu/OOTDiffusion#46]
![image](https://github.com/levihsu/OOTDiffusion/assets/33121696/63351d0e-1f47-40fb-9bfe-9a1cfa4182e2)
I also downloaded the model of openai, my directory structure is like this, execute the following command 'python run_ootd.py --model_path /home/ysm/tmmt/OOTDiffusion/run/examples/model/01008_00.jpg --cloth_path /home/ysm/tmmt/OOTDiffusion/run/examples/garment/00055_00.jpg --scale 2.0 --sample 4', and it works fine

_Originally posted by @nkTmmT in https://github.com/levihsu/OOTDiffusion/issues/29#issuecomment-1960594847_

**Comment by psksiu** [comment]
为什么我会“ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\embeddings.py)”
