### ISSUE TITLE
Module not found error: No module named 'cv2'

### ISSUE THREAD

**Issue by AWKohler** [levihsu/OOTDiffusion#48]
![Screenshot 2024-02-23 at 12 06 26 PM](https://github.com/levihsu/OOTDiffusion/assets/116976615/46279c1c-51fb-4a86-ab4a-ea69d4e7822c)

**Comment by devilkadabra69** [comment]
I GUESS CV2 IS NOT INSTALLED IN THE SYSTEM
try RUNNING 
pip install opencv-python
COMMAND BEFORE python run_ootd.py .. ......

**Comment by WGinit** [comment]
```bash
conda install -c conda-forge opencv
```
is ok

**Comment by levihsu** [comment]
pip install opencv-python
