### ISSUE TITLE
Any way to avoid hallucination and prevent print changes?

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [levihsu/OOTDiffusion#49]
Hello! I hope everyone is well! Firstly, I would like to thank you for making this incredible work available.

I'm doing some tests, and I've noticed some hallucinations. Apparently, the model reconstructs the clothing print, causing some differences in the final result.

I tried adjusting the parameters, but I couldn't resolve it.

Is there any way to get around the problem?

I know that the model must be in the early stages, and there is still a lot to be done, but I would like to know if I can do anything about it right now.

Thank you for your attention!

![image](https://github.com/levihsu/OOTDiffusion/assets/11933789/9cdbcfa5-5805-4f82-82fe-9ad1a1786303)

![image](https://github.com/levihsu/OOTDiffusion/assets/11933789/2e77dd02-00d9-4025-8dd9-361b07e76bb2)

**Comment by levihsu** [comment]
Hi! Thanks for your question. It is because the clothing features are learned in the latent space rather than being simply pasted. Please try larger guidance scales and different random seeds to get better results. We will continue improving the controllability of our model : )
