### ISSUE TITLE
How to train for a swimsuit

### ISSUE THREAD

**Issue by raofei** [levihsu/OOTDiffusion#5]
How to train on swimsuits that are actually treated as t-shirts when I offer swimsuits, and actually treated as long pants when I offer swim trunks
如何对泳装进行训练，当我提供泳衣的时候，实际上被当成了T恤，当我提供泳裤的时候，实际被当成了长裤
![01a](https://github.com/levihsu/OOTDiffusion/assets/6130056/5594c70d-6465-4e80-a1ff-42a37944eac5)

**Comment by levihsu** [comment]
你好 泳装的原图片可以发我看一下吗 半身模特换泳装上衣应该是可以的 全身模特长裤换泳裤因为训练数据的限制可能效果会有问题，除非模特本身也是穿短裤
