### ISSUE TITLE
Training tricks

### ISSUE THREAD

**Issue by ifeherva** [levihsu/OOTDiffusion#50]
Really impressive results, thanks for sharing.

I compared the weights of the unet with SD1.5 and if I am not mistaken the whole net was fine-tuned. What training tricks were used to avoid overfiting on such a small dataset like viton-hd?

**Comment by levihsu** [comment]
Thanks for your question. Both outfitting and denoising UNets are finetuned on the original SD1.5 UNet. The training details are mentioned in our paper, which will be released soon. Please stay tuned : )

**Comment by liupengcnu** [comment]
> Thanks for your question. Both outfitting and denoising UNets are finetuned on the original SD1.5 UNet. The training details are mentioned in our paper, which will be released soon. Please stay tuned : )

Hi, I noticed the the input channel of denoising UNets is 8, but the  input channel of SD1.5 UNet is 4, so how can you reused the SD1.5 UNet for denoising UNets?

**Comment by levihsu** [comment]
> > Thanks for your question. Both outfitting and denoising UNets are finetuned on the original SD1.5 UNet. The training details are mentioned in our paper, which will be released soon. Please stay tuned : )
> 
> Hi, I noticed the the input channel of denoising UNets is 8, but the input channel of SD1.5 UNet is 4, so how can you reused the SD1.5 UNet for denoising UNets?

We add a zero-initialized convolution to map it back to 4 channels.
