### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by jeffreyrobeson** [levihsu/OOTDiffusion#59]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 8.00 GiB total capacity; 14.21 GiB already allocated; 0 bytes free; 14.53 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by jeffreyrobeson** [comment]
我是用os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"这个来解决问题的

**Comment by yatoubusha** [comment]
> Please try setting sample=1 if your GPU memory is not enough

运行run_ootd.py，设置了sample=1，两张图片都是example里提供的，用24g显存的卡，还提示爆显存了，想问下这个脚本，需要多大的显卡才能支持？我这边有个警告是xformers不可用，是跟这个有关系吗？

**Comment by WHUZhangYuhan** [comment]
device：RTX3090
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.75GiB (GPU0; 23.68 GiB total capacity; 22.81 GiB already allocated; 161.94MiB free; 22.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by whaqzhzd** [comment]
I had the same problem
