### ISSUE TITLE
is runs on without CUDA ?

### ISSUE THREAD

**Issue by tzktz** [levihsu/OOTDiffusion#60]
i am using cpu..this model runs without  CUDA is possible?..thx in advance!!
@levihsu @ShineChen1024 @T-Gu

**Comment by levihsu** [comment]
Hi. We recommend using GPU for inference (2 RTX 4090 for us). Otherwise it will be very very slow...

**Comment by tzktz** [comment]
> Hi. We recommend using GPU for inference (2 RTX 4090 for us). Otherwise it will be very very slow...

ok but i want to run this in cpu ...i encounter below error @levihsu 
```
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

**Comment by levihsu** [comment]
Sorry, we've only tested our code on CUDA. You may encounter many unpredictable errors when using CPU and simply setting CUDA to FALSE won't solve them.

**Comment by tzktz** [comment]
> Sorry, we've only tested our code on CUDA. You may encounter many unpredictable errors when using CPU and simply setting CUDA to FALSE won't solve them.

ok thank u for ur reply!!!
