### ISSUE TITLE
Bad Results on Custom Images

### ISSUE THREAD

**Issue by mianemad** [levihsu/OOTDiffusion#63]
Hi, 

Amazing work here. I was just testing the model out and saw that with custom garment and person images the model performs really badly. Any reason for this?

**Comment by mianemad** [comment]
3:4 Images for the garment or the person?

**Comment by levihsu** [comment]
both

**Comment by mianemad** [comment]
The try on result is distorted still on custom in the wild images. is there a way to fix this?

**Comment by levihsu** [comment]
Please show me some examples, or try increasing guidance scale and adjusting random seed.

**Comment by mianemad** [comment]
![image](https://github.com/levihsu/OOTDiffusion/assets/86068953/3fb302e2-4622-43c8-b29b-d137f58ac960)
![image](https://github.com/levihsu/OOTDiffusion/assets/86068953/f011755b-8661-4134-b3f5-67bdcf62a97c)

**Comment by levihsu** [comment]
Please crop the garment image to make the clothes larger and make the background white
