### ISSUE TITLE
需求反馈

### ISSUE THREAD

**Issue by su-jianxin** [levihsu/OOTDiffusion#67]
1.需要身材性感的欧美模特如下，多次尝试发现效果基本都是会把胸部抹平或掩盖，如果可以自己上传模特并得到好的穿衣效果那会更好

![预期效果2](https://github.com/levihsu/OOTDiffusion/assets/129240037/145f6339-7aa2-4865-a133-88a440bd93a8)

**Comment by su-jianxin** [comment]
![image](https://github.com/levihsu/OOTDiffusion/assets/129240037/8bc68531-7ad7-403e-9518-71cecd9d0aa1)
效果是这样的，显得身材不好，不够吸引客户购买下单

**Comment by levihsu** [comment]
另外需要提醒，该项目严禁商用，请参考我们的license

**Comment by su-jianxin** [comment]
好的，方便问下目前是哪些场景支持使用呀

**Comment by su-jianxin** [comment]
请问目前什么场景支持商用呢


Yuhao Xu ***@***.***> 于2024年2月28日周三 17:46写道：
