### ISSUE TITLE
这种半身裙里用full-body用会穿不上，用穿裤子的模特会穿成裤子

### ISSUE THREAD

**Issue by biek12** [levihsu/OOTDiffusion#7]
<img width="265" alt="image" src="https://github.com/levihsu/OOTDiffusion/assets/25276878/554245b4-d9aa-4890-b1c7-3bc57a97e1d4">

**Comment by levihsu** [comment]
你好 这个问题确实存在哈 目前的建议是换下装的时候 衣服和原模特衣服类型尽量一致～
