### ISSUE TITLE
bad mask

### ISSUE THREAD

**Issue by habanerogossip** [levihsu/OOTDiffusion#72]
when I run the half body model I get bad output as a result of a bad mask. Any idea how to fix this?

![mask](https://github.com/levihsu/OOTDiffusion/assets/119080651/a7816a01-0a4c-4e81-91f3-26f70b1d6dd3)
![out_hd_0](https://github.com/levihsu/OOTDiffusion/assets/119080651/4abdbc30-5afe-4a0f-ac8e-50b5ccd598b7)

**Comment by levihsu** [comment]
It seems you are using wrong code or checkpoints for preprocess. Please check your files.

**Comment by habanerogossip** [comment]
ok likely related to code I pasted from this [issue](https://github.com/levihsu/OOTDiffusion/issues/51) in order to make it work on windows
