### ISSUE TITLE
哪个好心人能总结下，一步步搭建步骤！

### ISSUE THREAD

**Issue by renruiw** [levihsu/OOTDiffusion#73]
我在conda就卡住了。已经安装完毕了，但是提示找不到文件路径。但是环境变量也设置了。

**Comment by biaggii** [comment]
4 commands
git lfs clone https://huggingface.co/levihsu/OOTDiffusion
cd OOTDiffusion
pip install -r requirements.txt
python ./run/gradio_ootd.py

**Comment by renruiw** [comment]
Thank you very much. Concise and easy to understand :)
