### ISSUE TITLE
如何在本地启动Gradio demo？

### ISSUE THREAD

**Issue by lucifer726** [levihsu/OOTDiffusion#8]

**Comment by lucifer726** [comment]
raceback (most recent call last):
  File "/root/autodl-tmp/OOTDiffusion/run/graido_ootd.py", line 27, in <module>
    ootd_model_hd = OOTDiffusionHD(0)
  File "/root/autodl-tmp/OOTDiffusion/ootd/inference_ootd_hd.py", line 45, in __init__
    vae = AutoencoderKL.from_pretrained(
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/root/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 407, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it 
这个报错大佬知道怎么解决吗？

**Comment by lucifer726** [comment]
大佬，../checkpoints/ootd/ootd_dc/checkpoint-36000怎么下载啊

**Comment by JohnZero2023** [comment]
> 可以运行run文件夹下的graido_ootd.py

Prompt for missing files

**Comment by JohnZero2023** [comment]
![20240222174211](https://github.com/levihsu/OOTDiffusion/assets/149915749/8a03ac4a-f16b-4e53-bcb7-fae309bc02b1)

**Comment by pvbang** [comment]
@JohnZero2023 python run_ootd.py --model_path <model-image-path> --cloth_path <cloth-image-path> --scale 2.0 --sample 4 
![image](https://github.com/levihsu/OOTDiffusion/assets/89725712/d1b2f1e3-d4f5-46c7-893a-94ffbdce8aa8)

**Comment by SilentTE** [comment]
ValueError: Cannot load ../checkpoints/ootd/ootd_hd/checkpoint-36000 because conv_in.weight expected shape tensor
这个应该如何解决

**Comment by JohnZero2023** [comment]
> @JohnZero2023 python run_ootd.py --model_path --cloth_path --scale 2.0 --sample 4 ![image](https://private-user-images.githubusercontent.com/89725712/306947927-d1b2f1e3-d4f5-46c7-893a-94ffbdce8aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTk2NjAsIm5iZiI6MTcwODY1OTM2MCwicGF0aCI6Ii84OTcyNTcxMi8zMDY5NDc5MjctZDFiMmYxZTMtZDRmNS00NmM3LTg5M2EtOTRmZmJkY2U4YWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAzMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTI1OGI2OTY1OTNhZmVjODM4MGJiYTE1ZWExYzM2MDZkNDE1MzQ1MTg4MTUzYmE2MjE3YzJlYzkxNzBmODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iZOF9ksA0w6RU1zn4T6o_pWCW-zmhWikf6agrJO5CJg)

but gradio

**Comment by pvbang** [comment]
@JohnZero2023 try: pip install config
good luck :)))

**Comment by 2213601279** [comment]
你好，下载我建议同意下载huggingface 中的文件，具体路径为：https://huggingface.co/levihsu/OOTDiffusion
若无法下载，建议您这里使用 huggingface 镜像中的工具进行下载
wget https://hf-mirror.com/hfd/hfd.sh
chmod a+x hfd.sh
执行该命令即可下载
./hfd.sh levihsu/OOTDiffusion --tool aria2c -x 16
