### ISSUE TITLE
can anyone knows how to use this on any custom images with high quality results?

### ISSUE THREAD

**Issue by sudip550** [levihsu/OOTDiffusion#81]

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/issues/63#issuecomment-1966189185

**Comment by sudip550** [comment]
> [#63 (comment)](https://github.com/levihsu/OOTDiffusion/issues/63#issuecomment-1966189185)

Thank you for your response...... Can you tell us, when the advance version of this will release...

**Comment by levihsu** [comment]
The full-body model (dc) will be released next week.
