### ISSUE TITLE
gradio总算跑成功了，总结一下安装步骤

### ISSUE THREAD

**Issue by Spr-Peach** [levihsu/OOTDiffusion#88]
请看txt：
[installation.txt](https://github.com/levihsu/OOTDiffusion/files/14496328/installation.txt)

**Comment by Spr-Peach** [comment]
另外，不要python run\gradio_ootd.py，而是：
cd run
python gradio_ootd.py

**Comment by sehfdjajsj** [comment]
哥方便给个联系方式嘛我有点问题想请教一下

**Comment by Spr-Peach** [comment]
如果编译还是出错-例如出现界面后不能生成(提示”AttributeError: module 'inplace_abn' has no attribute 'forward'“等)，可以找一个取巧的办法：
[zhaoyun0071老师](https://github.com/zhaoyun0071)的gui项目：[OOTDiffusion-windows-GUI](https://github.com/zhaoyun0071/OOTDiffusion-windows-GUI)，下载到本地直接在项目根目录下找到inplace_abn.pyd文件，复制这个文件到OOTDiffusion的根目录下，修改preprocess\humanparsing\modules\functions.py，添加以下行：import inplace_abn (可以添加到之前添加的import inplace_abn as_backend的下一行)
如果懒得折腾可以试试我复制出来的文件：
[inplace_abn.zip](https://github.com/levihsu/OOTDiffusion/files/14495832/inplace_abn.zip)

**Comment by Spr-Peach** [comment]
> 哥方便给个联系方式嘛我有点问题想请教一下
如果还有问题试试我新添加的方法

**Comment by sehfdjajsj** [comment]
python: can't open file '/data/oy/OOTDiffusion/checkpoints/run_ootd.py': [Errno 2] No such file or directory

**Comment by sehfdjajsj** [comment]
Traceback (most recent call last):
  File "/data/oy/OOTDiffusion/run/run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/oy/OOTDiffusion/ootd/inference_ootd_hd.py", line 37, in __init__
    vae = AutoencoderKL.from_pretrained(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/oy/.env/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "/data/oy/.env/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ../checkpoints/ootd.

**Comment by Spr-Peach** [comment]
> python: can't open file '/data/oy/OOTDiffusion/checkpoints/run_ootd.py': [Errno 2] No such file or directory
这个问题...您当前路径位于checkpoints下，怎么能运行python run_ootd.py呢...py文件在run文件夹下...要先cd '/data/oy/OOTDiffusion/run然后再python run_ootd.py

**Comment by sehfdjajsj** [comment]
好的哥&nbsp; 我目前跑起来了 谢谢了&nbsp;


上帝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月6日(星期三) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [levihsu/OOTDiffusion] gradio总算跑成功了，总结一下安装步骤 (Issue #88)





  
python: can't open file '/data/oy/OOTDiffusion/checkpoints/run_ootd.py': [Errno 2] No such file or directory
 这个问题...您当前路径位于checkpoints下，怎么能运行python run_ootd.py呢...py文件在run文件夹下...要先cd '/data/oy/OOTDiffusion/run然后再python run_ootd.py

**Comment by sehfdjajsj** [comment]
git clone https://huggingface.co/levihsu/OOTDiffusion
git&nbsp;clone&nbsp;https://huggingface.co/openai/clip-vit-large-patch14
&nbsp;这两个我克隆不下来


上帝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "levihsu/OOTDiffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月6日(星期三) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [levihsu/OOTDiffusion] gradio总算跑成功了，总结一下安装步骤 (Issue #88)





  
python: can't open file '/data/oy/OOTDiffusion/checkpoints/run_ootd.py': [Errno 2] No such file or directory
 这个问题...您当前路径位于checkpoints下，怎么能运行python run_ootd.py呢...py文件在run文件夹下...要先cd '/data/oy/OOTDiffusion/run然后再python run_ootd.py

**Comment by chudaozhe** [comment]
> git clone https://huggingface.co/levihsu/OOTDiffusion git&nbsp;clone&nbsp;https://huggingface.co/openai/clip-vit-large-patch14 &nbsp;这两个我克隆不下来 上帝 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "levihsu/OOTDiffusion" ***@***.***&gt;; 发送时间:&nbsp;2024年3月6日(星期三) 下午5:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [levihsu/OOTDiffusion] gradio总算跑成功了，总结一下安装步骤 (Issue #88) python: can't open file '/data/oy/OOTDiffusion/checkpoints/run_ootd.py': [Errno 2] No such file or directory 这个问题...您当前路径位于checkpoints下，怎么能运行python run_ootd.py呢...py文件在run文件夹下...要先cd '/data/oy/OOTDiffusion/run然后再python run_ootd.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

给你个思路：github workflows + 阿里云容器镜像服务。前者负责克隆模型，构建镜像并上传镜像到阿里云，最后你只需要通过阿里云下载镜像，就能得到模型了

**Comment by sehfdjajsj** [comment]
上帝
***@***.***


preprocess.humanparsing.run_parsing  不存在是为啥
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "levihsu/OOTDiffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月16日(星期六) 晚上11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [levihsu/OOTDiffusion] gradio总算跑成功了，总结一下安装步骤 (Issue #88)





  
git clone https://huggingface.co/levihsu/OOTDiffusion git&nbsp;clone&nbsp;https://huggingface.co/openai/clip-vit-large-patch14 &nbsp;这两个我克隆不下来 上帝 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "levihsu/OOTDiffusion" @.&gt;; 发送时间:&nbsp;2024年3月6日(星期三) 下午5:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [levihsu/OOTDiffusion] gradio总算跑成功了，总结一下安装步骤 (Issue #88) python: can't open file '/data/oy/OOTDiffusion/checkpoints/run_ootd.py': [Errno 2] No such file or directory 这个问题...您当前路径位于checkpoints下，怎么能运行python run_ootd.py呢...py文件在run文件夹下...要先cd '/data/oy/OOTDiffusion/run然后再python run_ootd.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
给你个思路：github workflows + 阿里云容器镜像服务。前者负责克隆模型，构建镜像并上传镜像到阿里云，最后你只需要通过阿里云下载镜像，就能得到模型了

**Comment by Spr-Peach** [comment]
> 上帝 ***@***.*** preprocess.humanparsing.run_parsing 不存在是为啥 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "levihsu/OOTDiffusion" ***@***.***&gt;; 发送时间:&nbsp;2024年3月16日(星期六) 晚上11:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [levihsu/OOTDiffusion] gradio总算跑成功了，总结一下安装步骤 (Issue #88) git clone https://huggingface.co/levihsu/OOTDiffusion git&nbsp;clone&nbsp;https://huggingface.co/openai/clip-vit-large-patch14 &nbsp;这两个我克隆不下来 上帝 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "levihsu/OOTDiffusion" @.&gt;; 发送时间:&nbsp;2024年3月6日(星期三) 下午5:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [levihsu/OOTDiffusion] gradio总算跑成功了，总结一下安装步骤 (Issue #88) python: can't open file '/data/oy/OOTDiffusion/checkpoints/run_ootd.py': [Errno 2] No such file or directory 这个问题...您当前路径位于checkpoints下，怎么能运行python run_ootd.py呢...py文件在run文件夹下...要先cd '/data/oy/OOTDiffusion/run然后再python run_ootd.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 给你个思路：github workflows + 阿里云容器镜像服务。前者负责克隆模型，构建镜像并上传镜像到阿里云，最后你只需要通过阿里云下载镜像，就能得到模型了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

you can google these 2 keywords. the 1st: "HTTPS_PROXY   http://127.0.0.1:<port>"; the 2nd: ".gitconfig"...

**Comment by wengjiahua** [comment]
在其他国家打不开夸克怎么办

**Comment by chudaozhe** [comment]
> 在其他国家打不开夸克怎么办

回国！打不开夸克还搁那干什么？🐶
