### ISSUE TITLE
Was the VAE fine-tuned?

### ISSUE THREAD

**Issue by ifeherva** [levihsu/OOTDiffusion#92]
Thanks for sharing the paper, really detailed, very nice work. I hope it gets to the venue you submitted it to.

I compared the VAE weights with my VAE and it did not match so I am wondering which checkpoint did you use, or did you fine-tune it (the decoder)?

**Comment by levihsu** [comment]
Hi. Thanks for your question. We use a finetuned version of VAE to support high-resolution image reconstruction. The details are to be mentioned in our supplementary material later.
