### ISSUE TITLE
gradio速度好慢

### ISSUE THREAD

**Issue by liu124** [levihsu/OOTDiffusion#93]
系统配置cpu intel，GPU是P40*1，显存24G，内存是64G，需要15分钟，

**Comment by levihsu** [comment]
可能是配置不够。。我们用的RTX4090平均3秒一张

**Comment by liu124** [comment]
如果配置RTX4090能支持最大活跃人数使用？如果一台服务器配置多个台显卡速度会不会快些？我们服务目标在线100人，或者需要别的配置

**Comment by monyuan** [comment]
我也发现了这个问题，gradio下，4090跑了十三分钟

**Comment by ccl-private** [comment]
@levihsu 我用3090跑HD需要25秒，这个速度正常吗

**Comment by levihsu** [comment]
@ccl-private 感觉应该差不多吧
