### ISSUE TITLE
Seed has a big impact

### ISSUE THREAD

**Issue by mianemad** [levihsu/OOTDiffusion#95]
I have been testing different guidance values, steps and etc but one thing I have noticed is that the seed has a big impact. If randomly selecting seed with the guidance value and step the same, the final result will differ drastically based on seed. Any reason for this?

**Comment by levihsu** [comment]
Hi. I suppose it is common for SD-based models since the noise latent is randomly initialized based on the seed. While a larger guidance scale can preserve more clothing details whatever the seed is.

**Comment by mianemad** [comment]
But the difference is quite a lot. Any way to fix this this? Even at higher guidance scale it does not fix it.
