### ISSUE TITLE
About training details in paper

### ISSUE THREAD

**Issue by eiffiy** [levihsu/OOTDiffusion#96]
In the early version of our paper: 
"All the models are trained for 36000 iterations on a single NVIDIA A100 GPU, with a batch size of 64 for the 512×384 resolution and 16 for the 1024×768 resolution."
How you training for 1024x768 resolution  in batch size 16 on a single A100 ?

**Comment by levihsu** [comment]
Hi. We set mixed_precision="fp16" and use gradient_checkpointing. Then it is quite easy to train the model on a single A100 (80GB).

**Comment by eiffiy** [comment]
> Hi. We set mixed_precision="fp16" and use gradient_checkpointing. Then it is quite easy to train the model on a single A100 (80GB).

Did you use gradient_accumulation for training and  batchsize calculation?

**Comment by levihsu** [comment]
Nope

**Comment by puduliu** [comment]
I trained on a resolution of 512 x 384, batch size = 1, and used about 44G of GPU memory, but batch size = 2 directly increased more than 8 G. Is batch size = 64 unlikely?
